In [1]:
import pandas as pd

In [2]:
heart_disease = pd.read_csv("data/heart-disease.csv")

In [3]:
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [4]:
X = heart_disease.drop("target", axis=1)

In [5]:
Y = heart_disease["target"]

In [6]:
Y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [7]:
from sklearn.ensemble import RandomForestClassifier

In [8]:
clf = RandomForestClassifier(n_estimators=100)

In [9]:
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

In [12]:
clf.fit(X_train, Y_train)

RandomForestClassifier()

In [13]:
import numpy as np

In [14]:
X_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
186   60    1   0       130   253    0        1      144      1      1.4   
218   65    1   0       135   254    0        0      127      0      2.8   
243   57    1   0       152   274    0        1       88      1      1.2   
13    64    1   3       110   211    0        0      144      1      1.8   
280   42    1   0       136   315    0        1      125      1      1.8   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
206   59    1   0       110   239    0        0      142      1      1.2   
177   64    1   2       140   335    0        1      158      0      0.0   
32    44    1   1       130   219    0        0      188      0      0.0   
123   54    0   2       108   267    0        0      167      0      0.0   
106   69    1   3       160   234    1        0      131      0      0.1   

     slope  ca  thal  
186      2   1     3  
218      1   1     3  
243      1   1     3  
13       1   0     2  
280      1   0     1  
..     ...  ..   ...  
206      1   1     3  
177      2   0     2  
32       2   0     2  
123      2   0     2  
106      1   1     2  

[242 rows x 13 columns]

In [15]:
X_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
88    54    0   2       110   214    0        1      158      0      1.6   
20    59    1   0       135   234    0        1      161      0      0.5   
168   63    1   0       130   254    0        0      147      0      1.4   
154   39    0   2       138   220    0        1      152      0      0.0   
194   60    1   2       140   185    0        0      155      0      3.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
124   39    0   2        94   199    0        1      179      0      0.0   
66    51    1   2       100   222    0        1      143      1      1.2   
212   39    1   0       118   219    0        1      140      0      1.2   
5     57    1   0       140   192    0        1      148      0      0.4   
239   35    1   0       126   282    0        0      156      1      0.0   

     slope  ca  thal  
88       1   0     2  
20       1   0     3  
168      1   1     3  
154      1   0     2  
194      1   0     2  
..     ...  ..   ...  
124      2   0     2  
66       1   0     2  
212      1   0     3  
5        1   0     1  
239      2   0     3  

[61 rows x 13 columns]

In [16]:
clf.fit(X_train, Y_train)

RandomForestClassifier()

In [17]:
Y_preds = clf.predict(X_test)

In [18]:
Y_preds

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1])

In [19]:
clf.score(X_train,Y_train)

1.0

In [20]:
clf.score(X_test,Y_test)

0.7377049180327869

In [21]:
X_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
88    54    0   2       110   214    0        1      158      0      1.6   
20    59    1   0       135   234    0        1      161      0      0.5   
168   63    1   0       130   254    0        0      147      0      1.4   
154   39    0   2       138   220    0        1      152      0      0.0   
194   60    1   2       140   185    0        0      155      0      3.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
124   39    0   2        94   199    0        1      179      0      0.0   
66    51    1   2       100   222    0        1      143      1      1.2   
212   39    1   0       118   219    0        1      140      0      1.2   
5     57    1   0       140   192    0        1      148      0      0.4   
239   35    1   0       126   282    0        0      156      1      0.0   

     slope  ca  thal  
88       1   0     2  
20       1   0     3  
168      1   1     3  
154      1   0     2  
194      1   0     2  
..     ...  ..   ...  
124      2   0     2  
66       1   0     2  
212      1   0     3  
5        1   0     1  
239      2   0     3  

[61 rows x 13 columns]

In [22]:
from sklearn.metrics import confusion_matrix

In [23]:
print(confusion_matrix(Y_test, Y_preds))

[[15 11]
 [ 5 30]]


In [24]:
from sklearn.metrics import classification_report

In [25]:
print(classification_report(Y_test, Y_preds))

              precision    recall  f1-score   support

           0       0.75      0.58      0.65        26
           1       0.73      0.86      0.79        35

    accuracy                           0.74        61
   macro avg       0.74      0.72      0.72        61
weighted avg       0.74      0.74      0.73        61



In [26]:
np.random.seed(42)

In [27]:
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, Y_train)
    print(f"Model accruacy on test set: {clf.score(X_test, Y_test)}")
    print("")

Trying model with 10 estimators...
Model accruacy on test set: 0.7704918032786885

Trying model with 20 estimators...
Model accruacy on test set: 0.8032786885245902

Trying model with 30 estimators...
Model accruacy on test set: 0.7377049180327869

Trying model with 40 estimators...
Model accruacy on test set: 0.7704918032786885

Trying model with 50 estimators...
Model accruacy on test set: 0.7540983606557377

Trying model with 60 estimators...
Model accruacy on test set: 0.7704918032786885

Trying model with 70 estimators...
Model accruacy on test set: 0.8032786885245902

Trying model with 80 estimators...
Model accruacy on test set: 0.8032786885245902

Trying model with 90 estimators...
Model accruacy on test set: 0.7704918032786885



In [28]:
import pickle

In [29]:
pickle.dump(clf, open("random_forest_model_1.pkl", "wb"))

In [30]:
import sklearn

In [31]:
sklearn.show_versions()


System:
    python: 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 08:28:27) [Clang 14.0.6 ]
executable: /opt/anaconda3/bin/python
   machine: macOS-10.16-x86_64-i386-64bit

Python dependencies:
      sklearn: 1.5.1
          pip: 24.2
   setuptools: 75.1.0
        numpy: 1.26.4
        scipy: 1.13.1
       Cython: None
       pandas: 2.2.2
   matplotlib: 3.9.2
       joblib: 1.4.2
threadpoolctl: 3.5.0

Built with OpenMP: True

threadpoolctl info:
       user_api: blas
   internal_api: openblas
    num_threads: 8
         prefix: libopenblas
       filepath: /opt/anaconda3/lib/libopenblasp-r0.3.21.dylib
        version: 0.3.21
threading_layer: pthreads
   architecture: Haswell

       user_api: openmp
   internal_api: openmp
    num_threads: 16
         prefix: libomp
       filepath: /opt/anaconda3/lib/libomp.dylib
        version: None


In [32]:
car_sales_missing = pd.read_csv("data/car-sales-extended-missing-data.csv")
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [33]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [34]:
car_sales_missing.dropna(subset=["Price"], inplace=True)
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [35]:
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

# Split data into train and test
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2)

In [36]:
X.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
dtype: int64

In [37]:
# Fill missing values with Scikit-Learn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Fill categorical values with 'missing' & numerical values with mean
cat_imputer = SimpleImputer(strategy="constant", fill_value="missing")
door_imputer = SimpleImputer(strategy="constant", fill_value=4)
num_imputer = SimpleImputer(strategy="mean")

# Define columns
cat_features = ["Make", "Colour"]
door_feature = ["Doors"]
num_features = ["Odometer (KM)"]

# Create an imputer (something that fills missing data)
imputer = ColumnTransformer([
    ("cat_imputer", cat_imputer, cat_features),
    ("door_imputer", door_imputer, door_feature),
    ("num_imputer", num_imputer, num_features)
])

# Fill train and test values separately
filled_X_train = imputer.fit_transform(X_train)
filled_X_test = imputer.transform(X_test)

# Check filled X_train
filled_X_train

array([['Honda', 'White', 4.0, 71934.0],
       ['Toyota', 'Red', 4.0, 162665.0],
       ['Honda', 'White', 4.0, 42844.0],
       ...,
       ['Toyota', 'White', 4.0, 196225.0],
       ['Honda', 'Blue', 4.0, 133117.0],
       ['Honda', 'missing', 4.0, 150582.0]], dtype=object)

In [38]:
car_sales_filled_train = pd.DataFrame(filled_X_train, 
                                      columns=["Make", "Colour", "Doors", "Odometer (KM)"])

car_sales_filled_test = pd.DataFrame(filled_X_test, 
                                     columns=["Make", "Colour", "Doors", "Odometer (KM)"])

In [39]:
car_sales_filled_train.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [41]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", 
                                 one_hot, 
                                 categorical_features)],
                                 remainder="passthrough")

# Fill train and test values separately
transformed_X_train = transformer.fit_transform(car_sales_filled_train)
transformed_X_test = transformer.transform(car_sales_filled_test)

# Check transformed and filled X_train
transformed_X_train.toarray()

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 7.19340e+04],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.62665e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 4.28440e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.96225e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.33117e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.50582e+05]])

In [42]:
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

# Make sure to use transformed (filled and one-hot encoded X data)
model.fit(transformed_X_train, y_train)
model.score(transformed_X_test, y_test)

0.21229043336119102